// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

type CreateLinkTokenResponse struct {
	ContentType string
	// Successfully created link token
	CreateLinkTokenResponse *shared.CreateLinkTokenResponse
	StatusCode              int
	RawResponse             *http.Response
}
