// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// CreateObjectResponseBody - Successfully created object
type CreateObjectResponseBody struct {
	Object *shared.Object `json:"object,omitempty"`
}

func (o *CreateObjectResponseBody) GetObject() *shared.Object {
	if o == nil {
		return nil
	}
	return o.Object
}

type CreateObjectResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully created object
	Object *CreateObjectResponseBody
}

func (o *CreateObjectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateObjectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateObjectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateObjectResponse) GetObject() *CreateObjectResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
