// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// CreateSource200ApplicationJSON - Successfully created source
type CreateSource200ApplicationJSON struct {
	Source *shared.Source `json:"source,omitempty"`
}

type CreateSourceResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully created source
	CreateSource200ApplicationJSONObject *CreateSource200ApplicationJSON
}
