// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// CreateSourceResponseBody - Successfully created source
type CreateSourceResponseBody struct {
	Source *shared.Source `json:"source,omitempty"`
}

func (o *CreateSourceResponseBody) GetSource() *shared.Source {
	if o == nil {
		return nil
	}
	return o.Source
}

type CreateSourceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully created source
	Object *CreateSourceResponseBody
}

func (o *CreateSourceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateSourceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateSourceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateSourceResponse) GetObject() *CreateSourceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
