// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// CreateDestination200ApplicationJSON - Successfully created destination
type CreateDestination200ApplicationJSON struct {
	Destination *shared.Destination `json:"destination,omitempty"`
}

type CreateDestinationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully created destination
	CreateDestination200ApplicationJSONObject *CreateDestination200ApplicationJSON
}
