// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// CreateSync200ApplicationJSON - Successfully created sync
type CreateSync200ApplicationJSON struct {
	Sync *shared.Sync `json:"sync,omitempty"`
}

func (o *CreateSync200ApplicationJSON) GetSync() *shared.Sync {
	if o == nil {
		return nil
	}
	return o.Sync
}

type CreateSyncResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully created sync
	CreateSync200ApplicationJSONObject *CreateSync200ApplicationJSON
}

func (o *CreateSyncResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateSyncResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateSyncResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateSyncResponse) GetCreateSync200ApplicationJSONObject() *CreateSync200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CreateSync200ApplicationJSONObject
}
