// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// CreateSync200ApplicationJSON - Successfully created sync
type CreateSync200ApplicationJSON struct {
	Sync *shared.Sync `json:"sync,omitempty"`
}

type CreateSyncResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully created sync
	CreateSync200ApplicationJSONObject *CreateSync200ApplicationJSON
}
