// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

type CreateLinkTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successfully created link token
	CreateLinkTokenResponse *shared.CreateLinkTokenResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateLinkTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateLinkTokenResponse) GetCreateLinkTokenResponse() *shared.CreateLinkTokenResponse {
	if o == nil {
		return nil
	}
	return o.CreateLinkTokenResponse
}

func (o *CreateLinkTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateLinkTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
