// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// CreateObject200ApplicationJSON - Successfully created object
type CreateObject200ApplicationJSON struct {
	Object *shared.Object `json:"object,omitempty"`
}

type CreateObjectResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully created object
	CreateObject200ApplicationJSONObject *CreateObject200ApplicationJSON
}
