// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// GetDestinations200ApplicationJSON - Successfully fetched destinations
type GetDestinations200ApplicationJSON struct {
	Destinations []shared.Destination `json:"destinations,omitempty"`
}

type GetDestinationsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully fetched destinations
	GetDestinations200ApplicationJSONObject *GetDestinations200ApplicationJSON
}
