// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

type GetNamespacesRequest struct {
	ConnectionID int64 `queryParam:"style=form,explode=true,name=connectionID"`
}

type GetNamespacesResponse struct {
	ContentType string
	// Successfully fetched namespaces
	Namespaces  *shared.Namespaces
	StatusCode  int
	RawResponse *http.Response
}
