// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// GetObjectsResponseBody - Successfully fetched objects
type GetObjectsResponseBody struct {
	Objects []shared.Object `json:"objects,omitempty"`
}

func (o *GetObjectsResponseBody) GetObjects() []shared.Object {
	if o == nil {
		return nil
	}
	return o.Objects
}

type GetObjectsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully fetched objects
	Object *GetObjectsResponseBody
}

func (o *GetObjectsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetObjectsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetObjectsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetObjectsResponse) GetObject() *GetObjectsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
