// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// GetObjects200ApplicationJSON - Successfully fetched objects
type GetObjects200ApplicationJSON struct {
	Objects []shared.Object `json:"objects,omitempty"`
}

type GetObjectsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully fetched objects
	GetObjects200ApplicationJSONObject *GetObjects200ApplicationJSON
}
