// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// GetSources200ApplicationJSON - Successfully fetched sources
type GetSources200ApplicationJSON struct {
	Sources []shared.Source `json:"sources,omitempty"`
}

func (o *GetSources200ApplicationJSON) GetSources() []shared.Source {
	if o == nil {
		return nil
	}
	return o.Sources
}

type GetSourcesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully fetched sources
	GetSources200ApplicationJSONObject *GetSources200ApplicationJSON
}

func (o *GetSourcesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSourcesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSourcesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSourcesResponse) GetGetSources200ApplicationJSONObject() *GetSources200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetSources200ApplicationJSONObject
}
