// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

type GetSchemaRequest struct {
	ConnectionID int64  `queryParam:"style=form,explode=true,name=connectionID"`
	Namespace    string `queryParam:"style=form,explode=true,name=namespace"`
	TableName    string `queryParam:"style=form,explode=true,name=tableName"`
}

// GetSchema200ApplicationJSON - Successfully fetched schema
type GetSchema200ApplicationJSON struct {
	Schema []shared.Field `json:"schema,omitempty"`
}

type GetSchemaResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully fetched schema
	GetSchema200ApplicationJSONObject *GetSchema200ApplicationJSON
}
