// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// GetSourcesResponseBody - Successfully fetched sources
type GetSourcesResponseBody struct {
	Sources []shared.Source `json:"sources,omitempty"`
}

func (o *GetSourcesResponseBody) GetSources() []shared.Source {
	if o == nil {
		return nil
	}
	return o.Sources
}

type GetSourcesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully fetched sources
	Object *GetSourcesResponseBody
}

func (o *GetSourcesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSourcesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSourcesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSourcesResponse) GetObject() *GetSourcesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
