// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// GetSources200ApplicationJSON - Successfully fetched sources
type GetSources200ApplicationJSON struct {
	Sources []shared.Source `json:"sources,omitempty"`
}

type GetSourcesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully fetched sources
	GetSources200ApplicationJSONObject *GetSources200ApplicationJSON
}
