// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

// GetSyncs200ApplicationJSON - Successfully fetched syncs
type GetSyncs200ApplicationJSON struct {
	Syncs []shared.Sync `json:"syncs,omitempty"`
}

type GetSyncsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully fetched syncs
	GetSyncs200ApplicationJSONObject *GetSyncs200ApplicationJSON
}
