// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

type QueryObjectRequestBody struct {
	Filters []shared.QueryFilter `json:"filters,omitempty"`
}

func (o *QueryObjectRequestBody) GetFilters() []shared.QueryFilter {
	if o == nil {
		return nil
	}
	return o.Filters
}

type QueryObjectRequest struct {
	EndCustomerID string                  `pathParam:"style=simple,explode=false,name=endCustomerID"`
	ObjectID      int64                   `pathParam:"style=simple,explode=false,name=objectID"`
	RequestBody   *QueryObjectRequestBody `request:"mediaType=application/json"`
}

func (o *QueryObjectRequest) GetEndCustomerID() string {
	if o == nil {
		return ""
	}
	return o.EndCustomerID
}

func (o *QueryObjectRequest) GetObjectID() int64 {
	if o == nil {
		return 0
	}
	return o.ObjectID
}

func (o *QueryObjectRequest) GetRequestBody() *QueryObjectRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type ExampleField3 struct {
	NestedField1 *string `json:"nested_field_1,omitempty"`
	NestedField2 *int64  `json:"nested_field_2,omitempty"`
}

func (o *ExampleField3) GetNestedField1() *string {
	if o == nil {
		return nil
	}
	return o.NestedField1
}

func (o *ExampleField3) GetNestedField2() *int64 {
	if o == nil {
		return nil
	}
	return o.NestedField2
}

// QueryObjectResponseBody - The response payload will match the schema you defined when creating the object
type QueryObjectResponseBody struct {
	ExampleField1 *int64         `json:"example_field_1,omitempty"`
	ExampleField2 *string        `json:"example_field_2,omitempty"`
	ExampleField3 *ExampleField3 `json:"example_field_3,omitempty"`
}

func (o *QueryObjectResponseBody) GetExampleField1() *int64 {
	if o == nil {
		return nil
	}
	return o.ExampleField1
}

func (o *QueryObjectResponseBody) GetExampleField2() *string {
	if o == nil {
		return nil
	}
	return o.ExampleField2
}

func (o *QueryObjectResponseBody) GetExampleField3() *ExampleField3 {
	if o == nil {
		return nil
	}
	return o.ExampleField3
}

type QueryObjectResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The response payload will match the schema you defined when creating the object
	Object *QueryObjectResponseBody
}

func (o *QueryObjectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *QueryObjectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *QueryObjectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *QueryObjectResponse) GetObject() *QueryObjectResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
