// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/fabra-io/go-sdk/pkg/models/shared"
	"net/http"
)

type QueryObjectRequestBody struct {
	Filters []shared.QueryFilter `json:"filters,omitempty"`
}

type QueryObjectRequest struct {
	EndCustomerID string                  `pathParam:"style=simple,explode=false,name=endCustomerID"`
	ObjectID      int64                   `pathParam:"style=simple,explode=false,name=objectID"`
	RequestBody   *QueryObjectRequestBody `request:"mediaType=application/json"`
}

type QueryObject200ApplicationJSONExampleField3 struct {
	NestedField1 *string `json:"nested_field_1,omitempty"`
	NestedField2 *int64  `json:"nested_field_2,omitempty"`
}

// QueryObject200ApplicationJSON - The response payload will match the schema you defined when creating the object
type QueryObject200ApplicationJSON struct {
	ExampleField1 *int64                                      `json:"example_field_1,omitempty"`
	ExampleField2 *string                                     `json:"example_field_2,omitempty"`
	ExampleField3 *QueryObject200ApplicationJSONExampleField3 `json:"example_field_3,omitempty"`
}

type QueryObjectResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The response payload will match the schema you defined when creating the object
	QueryObject200ApplicationJSONObject *QueryObject200ApplicationJSON
}
