// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BigQueryConfig struct {
	Credentials *string `json:"credentials,omitempty"`
	Location    string  `json:"location"`
}
