// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Connection struct {
	ConnectionType *ConnectionType `json:"connection_type,omitempty"`
	ID             *int64          `json:"id,omitempty"`
}

func (o *Connection) GetConnectionType() *ConnectionType {
	if o == nil {
		return nil
	}
	return o.ConnectionType
}

func (o *Connection) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}
