// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ConnectionType string

const (
	ConnectionTypeSnowflake ConnectionType = "snowflake"
	ConnectionTypeBigquery  ConnectionType = "bigquery"
	ConnectionTypeRedshift  ConnectionType = "redshift"
	ConnectionTypeMongodb   ConnectionType = "mongodb"
	ConnectionTypeWebhook   ConnectionType = "webhook"
)

func (e ConnectionType) ToPointer() *ConnectionType {
	return &e
}

func (e *ConnectionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "snowflake":
		fallthrough
	case "bigquery":
		fallthrough
	case "redshift":
		fallthrough
	case "mongodb":
		fallthrough
	case "webhook":
		*e = ConnectionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionType: %v", v)
	}
}
