// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ConnectionTypeEnum string

const (
	ConnectionTypeEnumSnowflake ConnectionTypeEnum = "snowflake"
	ConnectionTypeEnumBigquery  ConnectionTypeEnum = "bigquery"
	ConnectionTypeEnumRedshift  ConnectionTypeEnum = "redshift"
	ConnectionTypeEnumMongodb   ConnectionTypeEnum = "mongodb"
	ConnectionTypeEnumWebhook   ConnectionTypeEnum = "webhook"
)

func (e ConnectionTypeEnum) ToPointer() *ConnectionTypeEnum {
	return &e
}

func (e *ConnectionTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "snowflake":
		fallthrough
	case "bigquery":
		fallthrough
	case "redshift":
		fallthrough
	case "mongodb":
		fallthrough
	case "webhook":
		*e = ConnectionTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionTypeEnum: %v", v)
	}
}
