// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateLinkTokenRequest struct {
	EndCustomerID string `json:"end_customer_id"`
}

func (o *CreateLinkTokenRequest) GetEndCustomerID() string {
	if o == nil {
		return ""
	}
	return o.EndCustomerID
}
