// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateLinkTokenResponse - Successfully created link token
type CreateLinkTokenResponse struct {
	LinkToken *string `json:"link_token,omitempty"`
}
