// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FieldMapping struct {
	DestinationFieldName *string `json:"destination_field_name,omitempty"`
	SourceFieldName      *string `json:"source_field_name,omitempty"`
}

func (o *FieldMapping) GetDestinationFieldName() *string {
	if o == nil {
		return nil
	}
	return o.DestinationFieldName
}

func (o *FieldMapping) GetSourceFieldName() *string {
	if o == nil {
		return nil
	}
	return o.SourceFieldName
}
