// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Field struct {
	Name *string        `json:"name,omitempty"`
	Type *FieldTypeEnum `json:"type,omitempty"`
}
