// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Field struct {
	Name *string    `json:"name,omitempty"`
	Type *FieldType `json:"type,omitempty"`
}

func (o *Field) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Field) GetType() *FieldType {
	if o == nil {
		return nil
	}
	return o.Type
}
