// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FrequencyUnits string

const (
	FrequencyUnitsMinutes FrequencyUnits = "minutes"
	FrequencyUnitsHours   FrequencyUnits = "hours"
	FrequencyUnitsDays    FrequencyUnits = "days"
	FrequencyUnitsWeeks   FrequencyUnits = "weeks"
)

func (e FrequencyUnits) ToPointer() *FrequencyUnits {
	return &e
}

func (e *FrequencyUnits) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "minutes":
		fallthrough
	case "hours":
		fallthrough
	case "days":
		fallthrough
	case "weeks":
		*e = FrequencyUnits(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FrequencyUnits: %v", v)
	}
}
