// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FrequencyUnitsEnum string

const (
	FrequencyUnitsEnumMinutes FrequencyUnitsEnum = "minutes"
	FrequencyUnitsEnumHours   FrequencyUnitsEnum = "hours"
	FrequencyUnitsEnumDays    FrequencyUnitsEnum = "days"
	FrequencyUnitsEnumWeeks   FrequencyUnitsEnum = "weeks"
)
