// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MongoDbConfig struct {
	ConnectionOptions *string `json:"connection_options,omitempty"`
	Host              string  `json:"host"`
	Password          string  `json:"password"`
	Username          string  `json:"username"`
}

func (o *MongoDbConfig) GetConnectionOptions() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionOptions
}

func (o *MongoDbConfig) GetHost() string {
	if o == nil {
		return ""
	}
	return o.Host
}

func (o *MongoDbConfig) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *MongoDbConfig) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
