// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Object struct {
	DestinationID *int64  `json:"destination_id,omitempty"`
	DisplayName   *string `json:"display_name,omitempty"`
	// This is where Fabra will insert the End Customer ID specified in the sync configuration
	EndCustomerIDField *string       `json:"end_customer_id_field,omitempty"`
	ID                 *int64        `json:"id,omitempty"`
	Namespace          *string       `json:"namespace,omitempty"`
	ObjectFields       []ObjectField `json:"object_fields,omitempty"`
	TableName          *string       `json:"table_name,omitempty"`
}

func (o *Object) GetDestinationID() *int64 {
	if o == nil {
		return nil
	}
	return o.DestinationID
}

func (o *Object) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *Object) GetEndCustomerIDField() *string {
	if o == nil {
		return nil
	}
	return o.EndCustomerIDField
}

func (o *Object) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Object) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *Object) GetObjectFields() []ObjectField {
	if o == nil {
		return nil
	}
	return o.ObjectFields
}

func (o *Object) GetTableName() *string {
	if o == nil {
		return nil
	}
	return o.TableName
}
