// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Object struct {
	DestinationID *int64  `json:"destination_id,omitempty"`
	DisplayName   *string `json:"display_name,omitempty"`
	// This is where Fabra will insert the End Customer ID specified in the sync configuration
	EndCustomerIDField *string       `json:"end_customer_id_field,omitempty"`
	ID                 *int64        `json:"id,omitempty"`
	Namespace          *string       `json:"namespace,omitempty"`
	ObjectFields       []ObjectField `json:"object_fields,omitempty"`
	TableName          *string       `json:"table_name,omitempty"`
}
