// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RedshiftConfig struct {
	DatabaseName string `json:"database_name"`
	Host         string `json:"host"`
	Password     string `json:"password"`
	Port         string `json:"port"`
	Username     string `json:"username"`
}

func (o *RedshiftConfig) GetDatabaseName() string {
	if o == nil {
		return ""
	}
	return o.DatabaseName
}

func (o *RedshiftConfig) GetHost() string {
	if o == nil {
		return ""
	}
	return o.Host
}

func (o *RedshiftConfig) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *RedshiftConfig) GetPort() string {
	if o == nil {
		return ""
	}
	return o.Port
}

func (o *RedshiftConfig) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
